// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe0i9LbqIqM0LpbbQ49DcYX3FFSePJvOU',
    appId: '1:769326469808:web:7958bce694e36d8e76e175',
    messagingSenderId: '769326469808',
    projectId: 'peminjaman-ruangan-6e7ca',
    authDomain: 'peminjaman-ruangan-6e7ca.firebaseapp.com',
    storageBucket: 'peminjaman-ruangan-6e7ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-OIlYA3H3mKWlg7R7DIKwxjn-ps-UfVA',
    appId: '1:769326469808:android:3ce24ef68178317d76e175',
    messagingSenderId: '769326469808',
    projectId: 'peminjaman-ruangan-6e7ca',
    storageBucket: 'peminjaman-ruangan-6e7ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe-JFevhK894lLfFLy4Nd52hru6LYPOtE',
    appId: '1:769326469808:ios:be1a9ce4e69307bf76e175',
    messagingSenderId: '769326469808',
    projectId: 'peminjaman-ruangan-6e7ca',
    storageBucket: 'peminjaman-ruangan-6e7ca.firebasestorage.app',
    iosBundleId: 'com.example.peminjamanRuangan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe-JFevhK894lLfFLy4Nd52hru6LYPOtE',
    appId: '1:769326469808:ios:be1a9ce4e69307bf76e175',
    messagingSenderId: '769326469808',
    projectId: 'peminjaman-ruangan-6e7ca',
    storageBucket: 'peminjaman-ruangan-6e7ca.firebasestorage.app',
    iosBundleId: 'com.example.peminjamanRuangan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe0i9LbqIqM0LpbbQ49DcYX3FFSePJvOU',
    appId: '1:769326469808:web:d06fb44c8723b7a276e175',
    messagingSenderId: '769326469808',
    projectId: 'peminjaman-ruangan-6e7ca',
    authDomain: 'peminjaman-ruangan-6e7ca.firebaseapp.com',
    storageBucket: 'peminjaman-ruangan-6e7ca.firebasestorage.app',
  );
}
